### ISSUE TITLE
Adding namespace causes whole core filer to be deleted and recreating. 

### ISSUE THREAD

**Issue by grant-ilm** [Azure/Avere#1340]
Given a corefiler that is already created with a namespace created, adding a namespace to the terraform causes the core filer to be removed and recreated rather than just adding the namespace.

**Comment by grant-ilm** [comment]
eg.
Original

core_filer {
        name = "filer1"
        ordinal = 1
        fixed_quota_percent = 65
        fqdn_or_primary_ip = "filer1.company.com"
        junction {
            namespace_path = "/root/dir/subdir1"
            core_filer_export = "/root/dir/subdir1"
        }
        junction {
            namespace_path = "/root/dir/subdir2"
            core_filer_export = "/root/dir/subdir2"
        }
}
If I change the terraform to the following, the plan indicates that the whole core filer will be deleted and recreated 
core_filer {
        name = "filer1"
        ordinal = 1
        fixed_quota_percent = 65
        fqdn_or_primary_ip = "filer1.company.com"
        junction {
            namespace_path = "/root/dir/subdir1"
            core_filer_export = "/root/dir/subdir1"
        }
        junction {
            namespace_path = "/root/dir/subdir2"
            core_filer_export = "/root/dir/subdir2"
        }
        junction {
            namespace_path = "/root/dir/subdir3"
            core_filer_export = "/root/dir/subdir3"
        }
}

**Comment by baileye** [comment]
For the current version of the Terraform vFXT provider this is the expected behaviour. It should only take 1-2 minutes to make a change like you have included in your example. I will note this is a feature request for future updates. Thank you!

**Comment by grant-ilm** [comment]
The reason I raised this is because it means that we can't do this change live using terraform. This impacts/limits the use of terraform post deployment.

**Comment by baileye** [comment]
Thanks for the additional information Grant. What you say makes perfect sense, I'll add it to the backlog and hopefully have something available for you to test soon.
