### ISSUE TITLE
Create an Azure RBAC role instructions. 

### ISSUE THREAD

**Issue by lagriffi** [Azure/Avere#68]
In the instructions for creating an Azure RBAC role ([link](https://github.com/Azure/Avere/blob/master/docs/prereqs.md#create-a-new-subscription)), it mentions editing the file to add the subscription ID, but it does not mention that the line above the subscription ID needs to be deleted:

![image](https://user-images.githubusercontent.com/42757948/45098923-0eb43500-b0f4-11e8-82c5-5b33d9dfff4a.png)

Can these instructions be updated to make it more clear that the Customer needs to both add their subscription ID and remove the line above the subscription ID?

**Comment by ekpgh** [comment]
The line that says "DELETE THIS LINE"? Sure. :)

**Comment by ekpgh** [comment]
Changed screenshot to show the instructions about deleting the line
