### ISSUE TITLE
Enable a read only cache policy with high write back delay

### ISSUE THREAD

**Issue by anhowe** [Azure/Avere#762]
Need to be able to create a policy like the following and apply it to a core filer:

cachePolicy.create "soft read only" "read" 10800

The approach will be to add this like the cloud workstation policies.

**Comment by baileye** [comment]
[Related commit](https://github.com/Azure/Avere/commit/b02f66b9171dfd3ab7a0a62d5d650af82faac4f6) to review and build upon for this issue

**Comment by baileye** [comment]
There was a misunderstanding in the configuration of the cache policy, it is not a high write back delay, but a high core filer verification time.
