### ISSUE TITLE
Terraform should have an option to allow managed identities

### ISSUE THREAD

**Issue by anhowe** [Azure/Avere#765]
Terraform should have an option to allow managed identities.  This will allow a user with Contributor access to deploy the Avere.

**Comment by jaos** [comment]
Assigning a managed identity to a VM requires "Managed Identity Operator".

**Comment by jswoodward** [comment]
The user will need "Managed Identity Operator" in order to assign a managed identity to a VM.

**Comment by anhowe** [comment]
## Development plan

1. Update controller module with option of managed identity
    * Controller - managed identity needs "Avere Contributor" and "Managed Identity Operator"

2. Add "user_assigned_managed_identity" field to provider - this will apply to vfxt.py.
    * the This managed identity needs "Avere Operator"
    * update documentation

3. update vfxt.py to accept user assigned managed identity needs "Avere Operator"

4. provide a working example complete with az cli commands on creating the necessary managed identity.
