### ISSUE TITLE
Filter '_' in vfxt cluster name

### ISSUE THREAD

**Issue by anhowe** [Azure/Avere#799]
https://github.com/Azure/Avere/blob/master/src/terraform/providers/terraform-provider-avere/resource_vfxt.go#L144 - should filter '_' chars.  Also check for other invalid chars rejected by vfxt.py.

**Comment by baileye** [comment]
Is this a rejection by vfxt.py because of an[ Azure resource naming](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules) convention being violated?
