### ISSUE TITLE
extend vdbench bootstrapper for slurm

### ISSUE THREAD

**Issue by tbugfinder** [Azure/Avere#803]
Hi,

thank you for all the content within this repo.
I'd like to use vdbench within a slurm+hpc cache deployment and thought it would be helpful if the bootstrap script `src/clientapps/vdbench/bootstrap.vdbench.sh` would directly support the execution within a Slurm deployment utilizing `SLURM_JOB_NODELIST`.

Thanks & Best

**Comment by tbugfinder** [comment]
I've adopted the script so that SLURM_JOB_NODES is evaluated.
I might create a PR as it might be useful for community.

**Comment by anhowe** [comment]
Thanks tbugfinder, a PR would be great as it would help the community, and we don't have a SLURM environment to test.
