### ISSUE TITLE
adding step in 'Enable Support' to using unique cluster name 

### ISSUE THREAD

**Issue by lianger114** [Azure/Avere#82]
https://github.com/Azure/Avere/blob/master/docs/enable_support.md

We need to add a step in the doc to have customer add an unique cluster name.  The name is how Avere support distinguish between which cluster when support bundle to upload to.  If its not filled, by default it will use the cluster name in Settings-> General Setup -> "Cluster name".  If the cluster name are the same for two cluster, the uploads will not work. 

Typically we suggest name of the company follow by alias of the cluster. 
For example.    microsoft-hpc1

For consistence, in the deploy doc. A step should also be added to use an unique name for the cluster when running vfxt.py script. 
https://github.com/Azure/Avere/blob/master/docs/jumpstart_deploy.md

**Comment by ekpgh** [comment]
This is fixed in the docs.microsoft.com version - https://docs.microsoft.com/en-us/azure/avere-vfxt/avere-vfxt-enable-support
