### ISSUE TITLE
Update Avere provider to support Terraform 0.13

### ISSUE THREAD

**Issue by anhowe** [Azure/Avere#844]
- update the provider
   - update the placement
   - update the libraries / sdk
- update the modules with the new dependencies
- review release notes, to see what else needs updating

**Comment by baileye** [comment]
https://www.terraform.io/upgrade-guides/0-13.html

**Comment by anhowe** [comment]
workaround for cloud shell for 0.12:

1. download and install terraform 0.12 to local bin directory
```bash
cd
mkdir -p ~/bin
wget https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip
unzip terraform_0.12.25_linux_amd64.zip
mv terraform bin
```

2. add the following line to ~/.bashrc
```bash
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
```

3. restart cloudshell

**Comment by anhowe** [comment]
For Terraform 0.13 and 0.14, use the techniques described here for the provider: https://www.terraform.io/docs/cli/config/config-file.html
